config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#index'

  get '/about', to: 'about#index'

  resources :blogs

end

#form action berrti mas ?

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_attached_file :thumbnail, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150>" }, default_url: "/images/:style/default.png"
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/

  def should_generate_new_friendly_id?
    title_changed?
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blogs = Blog.all
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :slug, :thumbnail, :content)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @blogs = Blog.all
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/about/index.html.erb
<div class="container" style="margin-top: 80px">
  <!-- Example row of columns -->
  <div class="row">

      <div class="col-md-3">
        <img src="https://www.bismalabs.co.id/resources/images/developer/fika.jpg" style="width: 200px;border-radius: 50%">
      </div>

      <div class="col-md-9">
        <p>
        <h3>Fika Ridaul Maulayya</h3>

        <span style="font-size: 18px;font-style: italic;font-weight: 300">Chief Technology Officer at Bisma Labs, seorang yang gemar mempelajari tentang dunia pemrogramman dan teknologi</span>
          <br>
          <a href="https://www.bismalabs.co.id">https://www.bismalabs.co.id</a>
        </p>
      </div>
  </div>



  </div>

app/views/blogs/_form.html.erb
<%= form_for @blog, html: {multipart: true } do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :thumbnail %>
      <%= f.file_field :thumbnail %>
    </div>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

  <!--
    <div class="field">
      <%= f.label :slug %>
      <%= f.text_field :slug %>
    </div>
  -->

    <div class="field">
      <%= f.label :content %>
      <%= f.text_area :content %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container" style="margin-top: 80px">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'New Blog', new_blog_path, class: 'btn btn-primary sm' %>
    </div>
    <% @blogs.each do |blog| %>
        <div class="col-md-4" style="margin-top: 20px">
                <div class="card" style="width: 20rem;">
                  <%= image_tag blog.thumbnail.url(:medium), class: 'card-img-top', style: ' min-height: 180px;max-height: 180px;' %>
                  <div class="card-body">
                    <h4 class="card-title"><%= blog.title %></h4>
                    <p class="card-text"><%= blog.content %></p>
                    <%= link_to edit_blog_path(blog), class: 'btn btn-danger sm' do %><i class="fa fa-pencil"></i> Edit <% end %>
                    <%= link_to blog, class: 'btn btn-primary sm' do %> Selengkapnya <i class="fa fa-external-link"></i><% end %>
                  </div>
                </div>
        </div>
      <% end %>
  </div>

</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container" style="margin-top: 80px">
  <!-- Example row of columns -->
  <div class="row">

    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <i class="fa fa-book"></i> <%= @blog.title %>
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p>
              <%= image_tag @blog.thumbnail.url(:original), style: 'width:100%;margin-bottom:10px;border-radius:20px' %>
              <%= @blog.content %>
            </p>
            <footer class="blockquote-footer"><%= @blog.updated_at %></footer>
          </blockquote>

          <p>
          <%= link_to 'Edit', edit_blog_path(@blog) %> |
          <%= link_to 'Back', blogs_path %>

        </div>

    </div>

    </div>

    <div class="col-md-4">
      <div class="list-group">
        <span class="list-group-item active" style="background-color: #343a40;border-color: #343a40">
          <i class="fa fa-book"></i> Most Popular Blog
        </span>
        <% @blogs.each do |blog| %>
          <a href="<%= blog.slug %>" class="list-group-item list-group-item-action"><i class="fa fa-long-arrow-right"></i> <%= blog.title %></a>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/homes/_form.html.erb
<%= form_for(home) do |f| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container text-center" style="margin-top: 20px">
    <h1 class="display-3" style="font-weight: 500"><img src="https://cdn4.iconfinder.com/data/icons/scripting-and-programming-languages/158/Ruby_on_Rails_2-512.png" style="width: 100px"> Hello, Rails!</h1>
    <p style="font-size: 20px"> I Create App Use Rails 5 + Bootsrap 4 + PostgreSQL  </p>
    <p><a class="btn btn-primary btn-lg" href="https://github.com/maulayyacyber/rails-bootsrap-v4.0.0-beta-postgres" role="button"><i class="fa fa-github"></i> See Repository </a></p>
  </div>
</div>

</div>
<div class="container" style="margin-top: 20px">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'New Blog', new_blog_path, class: 'btn btn-primary sm' %>
    </div>
    <% @blogs.each do |blog| %>
        <div class="col-md-4" style="margin-top: 20px">
          <div class="card" style="width: 20rem;">
            <%= image_tag blog.thumbnail.url(:medium), class: 'card-img-top', style: ' min-height: 180px;max-height: 180px;' %>
            <div class="card-body">
              <h4 class="card-title"><%= blog.title %></h4>
              <p class="card-text"><%= blog.content %></p>
              <%= link_to edit_blog_path(blog), class: 'btn btn-danger sm' do %><i class="fa fa-pencil"></i> Edit <% end %>
              <%= link_to blog, class: 'btn btn-primary sm' do %> Selengkapnya <i class="fa fa-external-link"></i><% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>

</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Rails With Bootstrap 4 and PostgreSQL</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="<%= root_path %>"><i class="fa fa-hashtag"></i> Rails App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= about_path %>">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= blogs_path %>">Blogs</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search Blog" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i> Search</button>
      </form>
    </div>
  </nav>

    <%= yield %>

  <hr>

  <footer>
    <p style="text-align: center">Copyright © 2017 Fika Ridaul Maulayya - Built with <a href="http://rubyonrails.org/" target="_blank">Rails</a> and <a href="https://www.postgresql.org/" target="_blank">PostgreSQL</a>, Deploy on <a href="https://www.heroku.com/" target="_blank"> Heroku.</a></p>
  </footer>
  </div> <!-- /container -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-eval': 'false' %>
  </body>
  </html>

</body>

</html>